LOCAL_PATH := $(call my-dir)

include $(CLEAR_VARS)
LOCAL_MODULE := RemovePkgs
LOCAL_MODULE_CLASS := APPS
LOCAL_MODULE_TAGS := optional
LOCAL_OVERRIDES_PACKAGES := YouTube
LOCAL_OVERRIDES_PACKAGES += Maps
LOCAL_OVERRIDES_PACKAGES += SafetyHubPrebuilt
LOCAL_OVERRIDES_PACKAGES += Drive
LOCAL_OVERRIDES_PACKAGES += PrebuiltGmail
LOCAL_OVERRIDES_PACKAGES += Camera2
LOCAL_OVERRIDES_PACKAGES += CameraGo
LOCAL_OVERRIDES_PACKAGES += Eleven
LOCAL_OVERRIDES_PACKAGES += GrapheneCamera
LOCAL_OVERRIDES_PACKAGES += AudioFX
LOCAL_OVERRIDES_PACKAGES += ViaPrebuilt
LOCAL_OVERRIDES_PACKAGES += GalleryGoPrebuilt
LOCAL_UNINSTALLABLE_MODULE := true
LOCAL_CERTIFICATE := PRESIGNED
LOCAL_SRC_FILES := /dev/null
include $(BUILD_PREBUILT)
